localPlanner:
  ros__parameters:
    vehicleLength: 0.6
    vehicleWidth: 0.6
    # sensorOffsetX: 0.0    #公共参数，这里修改注意修改其他地方 注意这个参数pathfollower这个脚本也用到了
    # sensorOffsetY: 0.0    #公共参数，这里修改注意修改其他地方注意这个参数pathfollower这个脚本也用到了
    # twoWayDrive: true   #公共参数，这里修改注意修改其他地方注意这个参数pathfollower这个脚本也用到了
    laserVoxelSize: 0.05
    terrainVoxelSize: 0.2
    useTerrainAnalysis: true
    checkObstacle: true
    checkRotObstacle: false
    adjacentRange: 4.25
    obstacleHeightThre: 0.15
    groundHeightThre: 0.1
    costHeightThre: 0.1
    costScore: 0.02
    useCost: false
    pointPerPathThre: 2
    minRelZ: -0.5
    maxRelZ: 0.25
    # maxSpeed: 2.0   #公共参数，这里修改注意修改其他地方注意这个参数pathfollower这个脚本也用到了
    dirWeight: 0.02
    dirThre: 90.0
    dirToVehicle: false
    pathScale: 1.25
    minPathScale: 0.75
    pathScaleStep: 0.25
    pathScaleBySpeed: true
    minPathRange: 1.0
    pathRangeStep: 0.5
    pathRangeBySpeed: true
    pathCropByGoal: true
    # autonomyMode: true   #公共参数，这里修改注意修改其他地方注意这个参数pathfollower这个脚本也用到了
    # autonomySpeed: 2.0   #公共参数，这里修改注意修改其他地方注意这个参数pathfollower这个脚本也用到了
    # joyToSpeedDelay: 2.0   #公共参数，这里修改注意修改其他地方注意这个参数pathfollower这个脚本也用到了
    joyToCheckObstacleDelay: 5.0
    goalClearRange: 0.5
    # goalX: 0.0   #公共参数，这里修改注意修改其他地方注意这个参数pathfollower这个脚本也用到了
    # goalY: 0.0   #公共参数，这里修改注意修改其他地方注意这个参数pathfollower这个脚本也用到了
    test_param: true